name: modern_ai_foundations
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch>=2.6.0
  - torchvision
  - ipykernel
  - ipywidgets
  - jupyter
  - pip:
      - -e .
      - transformers
      - datasets
      - matplotlib
      - python-dotenv
      - numpy
      - einops
      - scipy
      - tqdm
      - pillow
      - requests
      # For visual question answering
      - pytesseract
      - protobuf
